// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleDTO.Data;

namespace VehicleDTO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210601160531_InitialCreate-Part2")]
    partial class InitialCreatePart2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("VehicleDTO.Models.VehicleMakeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("VehicleMakeEntity");
                });

            modelBuilder.Entity("VehicleDTO.Models.VehicleModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MakeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId")
                        .IsUnique();

                    b.ToTable("VehicleModelEntity");
                });

            modelBuilder.Entity("VehicleDTO.Models.VehicleModelEntity", b =>
                {
                    b.HasOne("VehicleDTO.Models.VehicleMakeEntity", "VehicleMakeEntity")
                        .WithOne("VehicleModelEntity")
                        .HasForeignKey("VehicleDTO.Models.VehicleModelEntity", "MakeId")
                        .HasConstraintName("VehicleModelFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMakeEntity");
                });

            modelBuilder.Entity("VehicleDTO.Models.VehicleMakeEntity", b =>
                {
                    b.Navigation("VehicleModelEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
